### ISSUE TITLE
Processing errors

### ISSUE THREAD

**Issue by bigardone** [dashofcode/extracker#3]
If for instance you use a wrong `access_token` for listing projects, it throws the following error:

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for {403, %{code: "invalid_authentication", error: "Invalid authentication credentials were presented.", kind: "error", possible_fix: "Verify that your token value matches what's shown on your Profile page in Tracker."}}
```

Are you planning to add any backup for [API errors](https://www.pivotaltracker.com/help/api#Error_Responses)? I think it would be nice to have a new struct for them so it returns a more friendly error. I can create a new PR if you want :)

**Comment by forest** [comment]
I'd like to do as little error handling as possible and stick with the `let it crash` mantra. I'm still fairly new to elixir / erlang so I'm learning what this means in practice still. But there are lots of good articles on it. http://engineering-blog.alphasights.com/how-i-learned-to-stop-worrying-and-learned-to-love-the-crash/

That being said, the `Protocol.UndefinedError` isn't great. This should be getting to the `process_response` method and then getting a `FunctionClauseError` as a minimum.

Maybe for well defined API errors we handle those nicely, but others we let it crash and expect the user to handle it however they see fit.

Thoughts?
